### PR TITLE
Fix minimum Python version and add other items to help keep recipe up-to-date

### LINKED ISSUE #16: Incorrect minimum Python version
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The upstream repo reports minimum Python version of 3.8 (and may import typing.Protocol, which only exists in Python >=3.8).  However, this package reports python >=3.7 as dependency.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by DManowitz**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Fixes #16 

Added `pip check` to test section of recipe and `update-grayskull` to bot section of conda-forge.yml to help keep recipe up-to-date.

### CODE REVIEW

**Comment by DManowitz** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
@DManowitz thanks!

**Comment by carlodri** [comment]
@DManowitz pardon my ignorance, but what does the the `update-greyskull` thing encompass?

**Comment by DManowitz** [comment]
> @DManowitz pardon my ignorance, but what does the the `update-greyskull` thing encompass?

[Grayskull](https://github.com/conda/grayskull) is a package that is supposed to help with automated dependency updating in conda-forge.  See also [https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot](https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot) and/or [this conversation](https://github.com/conda-forge/conda-forge.github.io/issues/2062).

**Comment by carlodri** [comment]
thanks for the insight!

**Pull request merged**
